### ISSUE TITLE
Hierarchical planning

### ISSUE THREAD

**Issue by SmoLL-iCe** [SmoLL-iCe/VExDebugger#2]
# Todo

## Description
Here will be a list of things that need to be resolved in the future or new things I want to add.
This can take a good one until everything is done.

## Improvements
- [ ] Readme, explain better the project and give some examples of code
~- [ ] Structure the code for a main class to avoid so much global variable~
- [x] Change the samples interface

## Possible problems
- [x] Try to avoid any kind of racing conditions on the list or handlers

## Add new features / future ideas
- [ ] Spoof hardware breakpoints options
  - [ ] Using AddVectoredContinueHandler
  - [ ] Hooking NtGetThreadContext
  - [ ] Hooking NtContinue
- [x] Add trigger callback option **to use conditions**
~- [ ] Module or Threads Filters in the trigger, and exclude options~
- [x] Add instruction trace for breakpoint execution
- [x] Add other options for trigger breakpoints, type of software breakpoints or page guard
- [x] Hook using breakpoint

## References
* [x86 debug register](https://en.wikipedia.org/wiki/X86_debug_register)
* [Prefer Locks to Mutexes](https://www.modernescpp.com/index.php/prefer-locks-to-mutexes)

**Comment by matoqueimado** [comment]
apagou um monte de video em smoll 😢
